services:
  url-redirect:
    build: .
    init: true
    ports:
      - "8888:8080"
    volumes:
      - ./example:/mnt:rw
    environment:
      - CONFIG_FILE=/etc/url-redirect/config.toml
      - DB_FILE=/mnt/db.toml
